name: Create docker image
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/test/ecr/**'
      - 'terraform/modules/bluewhite/ecr/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/environments/test/ecr/**'
      - 'terraform/modules/bluewhite/ecr/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Install third-party dependencies
        run: |
          apt-get install -y zip curl

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          apt-get update
          apt-get dist-upgrade -y
          apt-get install -y less

      - name: Configure AWS credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=${AWS_REGION}" >> ~/.aws/config

      - name: Login to AWS
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 160213321344.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        env:
          App: bluewhite
          ECR_REGISTRY: 160213321344.dkr.ecr.eu-west-1.amazonaws.com
          ECR_REPOSITORY: bluewhite
          SHA:  ${{ github.sha }}
        run: |
          docker build -t $App app/ 
          docker tag $App $ECR_REGISTRY/$ECR_REPOSITORY:$SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
